language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-heavy-sails-angular' ]; then cd .. && eval "mv $currentfolder generator-heavy-sails-angular" && cd generator-heavy-sails-angular; fi

